### ISSUE TITLE
Cannot find module Source-map-support

### ISSUE THREAD

**Issue by thierryskoda** [palmerhq/backpack#42]
Hi, I'm trying to push my build on production and I'm getting this error

`Cannot find module '/Users/NAME/FOLDER/PROJECT_NAME/node_modules/source-map-support/source-map-support.js'`

Anyone know how to fix this?

Thank you very much!

**Comment by jaredpalmer** [comment]
Are you building somewhere differently than running in prod?

**Comment by thierryskoda** [comment]
I'm using heroku so I'm doing `backpack build` and then pushing the build folder (with `.Procfile` and `package.json`) to my heroku app.

**Comment by fibric** [comment]
I have the same issue on Windows 7 64bit Enterprise
`yarn start`
```
$ node ./build/main.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:codejsproductssfi.sebn.coackendattachment
ode_modulessource-map-supportsource-map-support.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\code\js\products\sfi.sebn.com\backend\attachment\build\main.js:1:63)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
error Command failed with exit code 1.
```

```es6
console.log(require.resolve('source-map-support'))
// C:\code\js\products\sfi.sebn.com\backend\attachment\node_modules\source-map-support\source-map-support.js
console.log(`require('${require.resolve('source-map-support')}')`)
// require('C:\code\js\products\sfi.sebn.com\backend\attachment\node_modules\source-map-support\source-map-support.js')
```

package.json extract
```json
"scripts": {
  "start": "node ./build/main.js",
  "prestart": "backpack build"
}
```

versions
```
node: '7.5.0'
yarn: '0.19.1'
backpack-core: '0.0.9'
```

**Comment by thierryskoda** [comment]
Do you think it's a best practice to build in production? I though it was much better to build locally than just push the build folder in production.

**Comment by jaredpalmer** [comment]
@thierryskoda When I pushed the change in `0.0.9` I had a feeling this would be an issue. The problem is that `lerna` doesn't handle the local npm symlink properly without that `require.resolve()`, which makes developing backpack really really annoying. We need to figure out a better solution.

As a workaround you should remove `webpack.BannerPlugin()` using `backpack.config.js`, add `source-map-support` as a dependency (npm i source-map-support), and then add `import 'source-map-support/register'` to the top of your entry file (`src/index.js` or whatever).

```js
// backpack.config.js
module.exports = {
  webpack: (config, options) => {
    ...
    config.plugins.splice(1, 1) // remove the BannerPlugin
    return config
  }
}
```

```js
//src/index.js or whatever
import 'source-map-support/register'
```

> Do you think it's a best practice to build in production? I though it was much better to build locally than just push the build folder in production.

Nowadays our build servers are the same VMs as our production machines so paths always match. However, I know that is not the case for everyone, especially for people using SaaS CI's and many PaaS providers. When we used to use Heroku with webpack or grunt, we used the `postinstall` npm script where to build on each deploy.

For example: 

```json
{
   "scripts": {
     ...
    "build": "backpack build",
    "postinstall": "npm run build"
  }
}
```

**Comment by ericclemmons** [comment]
I'll work on this!

**Comment by thierryskoda** [comment]
Okay thanks! I will try that!

**Comment by dortzur** [comment]
thank you @jaredpalmer Using both backpack and razzle on production systems and loving it

**Comment by ChiefORZ** [comment]
still having the same problem on windows 10 in both development and build.
project uses lerna and yarn workspaces.
using backpack version 0.7.0

**Comment by jalvarado91** [comment]
I'm having this issue when I try to run this on Docker. I have a build stage that compiles the `build/main.js` bundle and then removes all dev deps and any files that my app doesn't need, then I have another step that simply runs `npm start`. In theory that should be enough but into the same issue. 

```
> node ./build/main.js

module.js:550
    throw err;
    ^

Error: Cannot find module 'source-map-support/register'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
```

**Comment by idanwe** [comment]
@jalvarado91 did you solve that? we facing the same issue building docker image with multi stage

**Comment by MirKml** [comment]
still is the problem with docker builds as @jalvarado91 said

**Comment by vivere-dally** [comment]
Facing the same issue. The examples provided here did not help. Any news on fixing this?
